backend:
  name: git-gateway
  branch: main # o master según tu repo

media_folder: "assets/galeria"
public_folder: "/assets/galeria"

collections:
  - name: "galeria"
    label: "Galería"
    folder: "galeria"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
